version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=mysql://genascope:genascope@db:3306/genascope
    depends_on:
      - db
    command: ["./db-migration.sh"]
    networks:
      - genascope-network

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=genascope
      - MYSQL_USER=genascope
      - MYSQL_PASSWORD=genascope
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - genascope-network

volumes:
  mysql_data:

networks:
  genascope-network:
    driver: bridge